lqg_w_node: 
  ros__parameters:
    zero_speed  : 0.0
    max_speed : 2.0 
    min_speed : 0.363 
    error_threshold : 0.09 
    max_right_steering : 0.4 
    max_left_steering : -0.4
    Ts : 0.05
    data_out_name : "kalman_test5"
    data_out_location : "/home/projects/ros2_ws/src/ucsd_robocar_hub2/ucsd_robocar_control2_pkg/data/"
