pid_node: 
  ros__parameters: 
    Kp_steering : 1.0 
    Ki_steering : 1.0E-8 
    Kd_steering : 1.0E-1
    integral_max: 1.0E-7
    zero_speed  : 0.0
    max_speed : 0.4 
    min_speed : 0.4 
    upper_error_threshold : 0.40 
    lower_error_threshold : 0.10 
    max_right_steering : 0.4 
    max_left_steering : -0.4
