pid_node: 
  ros__parameters: 
    Kp_steering : 0.3 
    Ki_steering : 0.0 
    Kd_steering : 0.0 
    zero_throttle  : -0.032
    max_throttle : 0.382 
    min_throttle : 0.363 
    error_threshold : 0.16 
    max_right_steering : 0.792 
    max_left_steering : -0.831 
